CREATE TABLE USER_U (
	USER_NO	NUMBER	PRIMARY KEY,
	USER_ID	VARCHAR2(30)	NOT NULL,
	USER_PW	VARCHAR2(100)	NOT NULL,
	USER_DATE	DATE	DEFAULT sysdate 
);

CREATE TABLE WRITE_W (
	WRITE_NO	NUMBER	PRIMARY KEY,
	USER_NO	NUMBER	NOT NULL,
	WRITE_TITLE	VARCHAR(40)	NOT NULL,
	WRITE_CONTENT	VARCHAR2(300)	NOT NULL,
	WRITE_DATE	DATE	DEFAULT sysdate 
);

CREATE TABLE WRITE_R (
	WRITE_NO	NUMBER	PRIMARY KEY,
	USER_NO	NUMBER	NOT NULL,
	WRITE_TITLE	VARCHAR(40)	NOT NULL,
	WRITE_CONTENT	VARCHAR2(300)	NOT NULL,
	WRITE_DATE	DATE	DEFAULT sysdate 
);

COMMIT;

SELECT WRITE_NO, USER_NO, WRITE_TITLE, WRITE_CONTENT, WRITE_DATE
FROM WRITE_W;


ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_NO`
);

ALTER TABLE `WRITE` ADD CONSTRAINT `PK_WRITE` PRIMARY KEY (
	`WRITE_NO`,
	`USER_NO`
);

ALTER TABLE WRITE_W ADD CONSTRAINT FK_USER_TO_WRITE_1 FOREIGN KEY (
	USER_NO
)
REFERENCES USER_U (
	USER_NO
);

COMMIT;

SELECT *
FROM USER_U;

SELECT * FROM USER_U 
WHERE USER_ID = 'jim'
AND USER_PW = '12345';

CREATE SEQUENCE SEQ_USER_U_no nocache;

INSERT INTO USER_U(USER_NO, USER_ID, USER_PW, USER_DATE)
 VALUES(SEQ_USER_U_NO.NEXTVAL, 'jin', '1234', DEFAULT);
