CREATE TABLE USER_U (
	USER_NO	NUMBER	PRIMARY KEY,
	USER_ID	VARCHAR2(30)	NOT NULL,
	USER_PW	VARCHAR2(100)	NOT NULL,
	USER_DATE	DATE	DEFAULT sysdate 
);

CREATE TABLE WRITE_W (
	WRITE_NO	NUMBER	PRIMARY KEY,
	USER_NO	NUMBER	NOT NULL,
	WRITE_TITLE	VARCHAR(40)	NOT NULL,
	WRITE_CONTENT	VARCHAR2(300)	NOT NULL,
	WRITE_DATE	DATE	DEFAULT sysdate 
);

CREATE TABLE WRITE_R (
	WRITE_NO	NUMBER	PRIMARY KEY,
	USER_NO	NUMBER	NOT NULL,
	WRITE_TITLE	VARCHAR(40)	NOT NULL,
	WRITE_CONTENT	VARCHAR2(300)	NOT NULL,
	WRITE_DATE	DATE	DEFAULT sysdate 
);

ALTER TABLE WRITE_W DROP CONSTRAINT unique_user_id;
ALTER TABLE WRITE_R DROP CONSTRAINT unique_user_id;
ALTER TABLE WRITE_H DROP CONSTRAINT unique_user_id;

SELECT *
FROM WRITE_R
WHERE WRITE_TITLE != 'sad';

COMMIT;

ALTER TABLE WRITE_W DROP CONSTRAINT unique_user_id;
ALTER TABLE WRITE_R DROP CONSTRAINT unique_user_id;
ALTER TABLE WRITE_H DROP CONSTRAINT unique_user_id;

COMMIT;

CREATE TABLE WRITE_H (
	WRITE_NO	NUMBER	PRIMARY KEY,
	USER_NO	NUMBER	NOT NULL,
	WRITE_TITLE	VARCHAR(40)	NOT NULL,
	WRITE_CONTENT	VARCHAR2(300)	NOT NULL,
	WRITE_DATE	DATE	DEFAULT sysdate 
);

COMMIT;

SELECT WRITE_NO, USER_NO, WRITE_TITLE, WRITE_CONTENT, WRITE_DATE
FROM WRITE_W;


ALTER TABLE USER_U ADD CONSTRAINT PK_USER PRIMARY KEY (
	USER_NO
);

ALTER TABLE WRITE_W ADD CONSTRAINT PK_WRITE PRIMARY KEY (
	WRITE_NO
);

ALTER TABLE WRITE_R ADD CONSTRAINT FK_USER_TO_WRITE_2 FOREIGN KEY (
	USER_NO
)
REFERENCES USER_U (
	USER_NO
);

COMMIT;

SELECT *
FROM USER_U;

DELETE FROM USER_U
WHERE USER_NO = '3';

SELECT * FROM USER_U 
WHERE USER_ID = 'jim'
AND USER_PW = '12345';



INSERT INTO WRITE_W
SELECT * FROM WRITE_R WHERE USER_NO = ?;

INSERT INTO WRITE_R(WRITE_NO, USER_NO, WRITE_TITLE, WRITE_CONTENT, WRITE_DATE)
VALUES(SEQ_WRITE_NO.NEXTVAL, ?, ?, ?, DEFAULT);

COMMIT;
 

CREATE SEQUENCE SEQ_USER_NO nocache;

COMMIT;

ALTER TABLE WRITE_H
ADD USER_ID VARCHAR2(50);

SELECT *
FROM WRITE_R;

SELECT * FROM WRITE_W;

INSERT INTO USER_U(USER_NO, USER_ID, USER_PW, USER_DATE)
 VALUES(SEQ_USER_U_NO.NEXTVAL, 'jin', '1234', DEFAULT);
