CREATE TABLE C##EDU_USER.A_OUT_M 
(
BRAND_CD VARCHAR2(30 BYTE),
INVOICE_NO VARCHAR2(30 BYTE),
OUTBOUND_DATE DATE,
OUT_TYPE_DIV VARCHAR2(30 BYTE),
ORDER_NM VARCHAR2(30 BYTE),
CONSTRAINT A_OUT_M_PK PRIMARY KEY (BRAND_CD, INVOICE_NO),
CONSTRAINT A_OUT_M_FK1 FOREIGN KEY (BRAND_CD) REFERENCES C##EDU_USER.A_BRAND (BRAND_CD)
)
TABLESPACE TS_EDU_BASE;

COMMENT ON TABLE C##EDU_USER.A_OUT_M IS '주문(HEADER)';
COMMENT ON COLUMN C##EDU_USER.A_OUT_M.BRAND_CD IS '브랜드코드';
COMMENT ON COLUMN C##EDU_USER.A_OUT_M.INVOICE_NO IS '송장번호';
COMMENT ON COLUMN C##EDU_USER.A_OUT_M.OUTBOUND_DATE IS '출고일자';
COMMENT ON COLUMN C##EDU_USER.A_OUT_M.OUT_TYPE_DIV IS '출고유형구분';
COMMENT ON COLUMN C##EDU_USER.A_OUT_M.ORDER_NM IS '주문자';


CREATE TABLE C##EDU_USER.A_OUT_D
( 
BRAND_CD VARCHAR2(30 BYTE),
INVOICE_NO VARCHAR2(30 BYTE),
LINE_NO NUMBER,
ITEM_CD VARCHAR2(30 BYTE),
ORDER_QTY NUMBER,
CONSTRAINT A_OUT_D_PK PRIMARY KEY (BRAND_CD, INVOICE_NO, LINE_NO),
CONSTRAINT A_OUT_D_FK1 FOREIGN KEY (BRAND_CD, ITEM_CD) REFERENCES C##EDU_USER.A_ITEM (BRAND_CD, ITEM_CD)
)
TABLESPACE TS_EDU_BASE;


COMMENT ON TABLE C##EDU_USER.A_OUT_D IS '주문상세(BODY)';
COMMENT ON COLUMN C##EDU_USER.A_OUT_D.BRAND_CD IS '브랜드코드';
COMMENT ON COLUMN C##EDU_USER.A_OUT_D.INVOICE_NO IS '송장번호';
COMMENT ON COLUMN C##EDU_USER.A_OUT_D.LINE_NO IS '순번';
COMMENT ON COLUMN C##EDU_USER.A_OUT_D.ITEM_CD IS '상품코드';
COMMENT ON COLUMN C##EDU_USER.A_OUT_D.ORDER_QTY IS '출고수량';


INSERT INTO A_BRAND
VALUES('1001', '나이키');

INSERT INTO A_ITEM
VALUES('1001', '100', '나이키', '1');

UPDATE A_ITEM
SET ITEM_CD = '102';


SELECT * FROM A_BRAND;

INSERT INTO A_BRAND
VALUES('1002', '아디다스');

UPDATE A_BRAND
SET BRAND_CD = '2001';

DELETE FROM A_ITEM
WHERE ITEM_CD = '1001';

INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('1001', 'A', '상품A', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('1001', 'B', '상품B', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('1001', 'C', '상품C', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('1001', 'D', '상품D', 3);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('1001', 'E', '상품E', 3);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('2001', 'A', '상품A', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('2001', 'B', '상품B', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('2001', 'C', '상품C', 2);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('2001', 'D', '상품D', 3);
INSERT INTO A_ITEM (BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX) VALUES('2001', 'E', '상품E', 3);


INSERT INTO A_OUT_M VALUES ('1001', '#01', TO_DATE('20230103', 'YYYY-MM-DD'), 'M11', '윤현수');
INSERT INTO A_OUT_M VALUES ('1001', '#02', TO_DATE('20230103', 'YYYY-MM-DD'), 'M11', '전정훈');
INSERT INTO A_OUT_M VALUES ('1001', '#03', TO_DATE('20230104', 'YYYY-MM-DD'), 'M12', '고선주');
INSERT INTO A_OUT_M VALUES ('1001', '#04', TO_DATE('20230105', 'YYYY-MM-DD'), 'M12', '최재원');
INSERT INTO A_OUT_M VALUES ('1001', '#05', TO_DATE('20230105', 'YYYY-MM-DD'), 'M21', '권민재');
INSERT INTO A_OUT_M VALUES ('1001', '#06', TO_DATE('20230103', 'YYYY-MM-DD'), 'M11', '강민규');
INSERT INTO A_OUT_M VALUES ('1001', '#07', TO_DATE('20230104', 'YYYY-MM-DD'), 'M21', '김민기');
INSERT INTO A_OUT_M VALUES ('1001', '#08', TO_DATE('20230104', 'YYYY-MM-DD'), 'M22', '김민기');
INSERT INTO A_OUT_M VALUES ('1001', '#09', TO_DATE('20230104', 'YYYY-MM-DD'), 'M22', '조승완');
INSERT INTO A_OUT_M VALUES ('1001', '#10', TO_DATE('20230105', 'YYYY-MM-DD'), 'M22', '진효인');


INSERT INTO A_OUT_D VALUES ('1001', '#02', 1, 'B', 1);
INSERT INTO A_OUT_D VALUES ('1001', '#02', 2, 'C', 3);
INSERT INTO A_OUT_D VALUES ('1001', '#03', 1, 'B', 2);
INSERT INTO A_OUT_D VALUES ('1001', '#04', 1, 'A', 1);
INSERT INTO A_OUT_D VALUES ('1001', '#04', 2, 'D', 1);
INSERT INTO A_OUT_D VALUES ('1001', '#04', 3, 'E', 2);
INSERT INTO A_OUT_D VALUES ('1001', '#05', 1, 'C', 5);
INSERT INTO A_OUT_D VALUES ('1001', '#01', 1, 'A', 1);
INSERT INTO A_OUT_D VALUES ('2001', '#01', 2, 'B', 2);
INSERT INTO A_OUT_D VALUES ('2001', '#07', 1, 'E', 1);
INSERT INTO A_OUT_D VALUES ('2001', '#08', 1, 'C', 1);
INSERT INTO A_OUT_D VALUES ('2001', '#09', 1, 'B', 3);
INSERT INTO A_OUT_D VALUES ('2001', '#09', 2, 'D', 1);
INSERT INTO A_OUT_D VALUES ('2001', '#10', 1, 'E', 1);
INSERT INTO A_OUT_D VALUES ('2001', '#01', 1, 'A', 1);

COMMIT;

SELECT COUNT(1) FROM A_BRAND
UNION ALL
SELECT COUNT(1) FROM A_ITEM
UNION ALL 
SELECT COUNT(1) FROM A_OUT_M
UNION ALL
SELECT COUNT(1) FROM A_OUT_D;

SELECT BRAND_CD
FROM A_BRAND;

SELECT DISTINCT BRAND_CD, OUTBOUND_DATE
FROM A_OUT_M;

SELECT BRAND_CD, OUTBOUND_DATE
FROM A_OUT_M
GROUP BY BRAND_CD, OUTBOUND_DATE;

SELECT * FROM A_OUT_M
WHERE BRAND_CD = '1001'
AND   OUT_TYPE_DIV = 'M12';

SELECT * FROM A_OUT_M
WHERE BRAND_CD = '1001'
-- AND   OUT_TYPE_DIV IN ('M11', 'M12');
AND   OUT_TYPE_DIV IN ('M11', 'M12');

SELECT * 
FROM A_OUT_M
WHERE OUT_TYPE_DIV IN ('M11', 'M12')
AND INVOICE_NO BETWEEN '#01' AND '#03';

SELECT * 
FROM A_OUT_M
WHERE OUT_TYPE_DIV IN ('M11', 'M12')
AND INVOICE_NO BETWEEN '#01' AND '#03'
AND OUT_TYPE_DIV LIKE '%1';

SELECT *
FROM A_OUT_M
WHERE OUT_TYPE_DIV IN ('M11', 'M12')
AND INVOICE_NO BETWEEN '#01' AND '#03'
ORDER BY OUTBOUND_DATE DESC, BRAND_CD;

SELECT BRAND_CD, OUT_TYPE_DIV, COUNT(*) AS CNT
FROM A_OUT_M M
WHERE OUT_TYPE_DIV IN ('M11', 'M12')
AND INVOICE_NO BETWEEN '#01' AND '#03'
GROUP BY BRAND_CD, OUT_TYPE_DIV
HAVING COUNT(*) = 2;



