SELECT BRAND_CD, COUNT(*) AS INVOICE
FROM A_OUT_M
GROUP BY BRAND_CD; 


SELECT BRAND_CD, ITEM_CD, COUNT(*)
FROM A_OUT_D
WHERE BRAND_CD IN '1001'
AND ITEM_CD IN 'A'
GROUP BY BRAND_CD, ITEM_CD
ORDER BY BRAND_CD;


SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, COUNT(*)
FROM A_OUT_M
WHERE BRAND_CD IN ('1001', '2001')
AND OUTBOUND_DATE IN '2023-01-03'
GROUP BY BRAND_CD, INVOICE_NO, OUTBOUND_DATE
ORDER BY BRAND_CD;


SELECT * FROM A_OUT_M;
SELECT * FROM A_OUT_D;
SELECT * FROM A_ITEM;


SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM
FROM A_OUT_M
WHERE OUTBOUND_DATE IN '2023-01-03'
GROUP BY BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM;


SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM
FROM A_OUT_M
WHERE OUTBOUND_DATE IN '2023-01-04'
AND ORDER_NM IN '±è¹Î±â'
GROUP BY BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM;


SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
FROM A_OUT_D
WHERE ITEM_CD IN 'A'
GROUP BY BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY;


SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
FROM A_OUT_D
WHERE ITEM_CD IN 'C'
AND ORDER_QTY >= 3
GROUP BY BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY;


SELECT BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX
FROM A_ITEM
WHERE BRAND_CD IN '1001'
GROUP BY BRAND_CD, ITEM_CD, ITEM_NM, QTY_IN_BOX;

