-- Sample 자료 및 연습 1번
SELECT BRAND_CD, COUNT(*) AS INVOICE
FROM A_OUT_M
GROUP BY BRAND_CD; 

-- Sample 자료 및 연습 2번
SELECT BRAND_CD, ITEM_CD, COUNT(*)
FROM A_OUT_D
WHERE BRAND_CD IN '1001'
AND ITEM_CD IN 'A'
GROUP BY BRAND_CD, ITEM_CD
ORDER BY BRAND_CD;

-- Sample 자료 및 연습 3번 - 1
SELECT BRAND_CD, ITEM_CD, SUM(ORDER_QTY)
FROM A_OUT_D
WHERE (BRAND_CD, INVOICE_NO) IN (
SELECT BRAND_CD, INVOICE_NO
FROM A_OUT_M
WHERE OUTBOUND_DATE = '2023-01-03'
)
GROUP BY BRAND_CD, ITEM_CD
ORDER BY BRAND_CD, ITEM_CD;

-- Sample 자료 및 연습 3번 - 2
SELECT M2.BRAND_CD, M2.ITEM_CD, SUM(M2.ORDER_QTY) 
FROM A_OUT_M M1 
JOIN A_OUT_D M2 ON  M2.BRAND_CD = M1.BRAND_CD
AND M2.INVOICE_NO = M1.INVOICE_NO
WHERE M1.OUTBOUND_DATE = '2023-01-03'
GROUP BY M2.BRAND_CD, M2.ITEM_CD
ORDER BY M2.BRAND_CD, M2.ITEM_CD;





-- SELECT FROM 
SELECT * FROM A_OUT_M;
SELECT * FROM A_OUT_D;
SELECT * FROM A_ITEM;

-- SELECT FROM WHERE 1번
SELECT * FROM A_OUT_M
WHERE OUTBOUND_DATE = '2023-01-03';

-- SELECT FROM WHERE 2번
SELECT * FROM A_OUT_M
WHERE OUTBOUND_DATE = '2023-01-04'
AND ORDER_NM = '김민기';

-- SELECT FROM WHERE 3번
SELECT * FROM A_OUT_D
WHERE ITEM_CD = 'A';

-- SELECT FROM WHERE 4번
SELECT * FROM A_OUT_D
WHERE ITEM_CD = 'C'
AND ORDER_QTY >= 3;

-- SELECT FROM WHERE 5번
SELECT * FROM A_ITEM
WHERE BRAND_CD = '1001';


-- SELECT FROM WHERE(IN) 1번
SELECT BRAND_CD, INVOICE_NO, ORDER_NM
FROM A_OUT_M
WHERE OUTBOUND_DATE IN ('2023-01-03', '2023-01-04');

-- SELECT FROM WHERE(IN) 2번
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
FROM A_OUT_D
WHERE BRAND_CD = '1001' 
AND ITEM_CD IN ('A', 'B', 'C')
AND ORDER_QTY >= 3;

-- SELECT FROM WHERE(BETWEEN) 1번
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
FROM A_OUT_M
WHERE OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
AND ORDER_NM IN ('윤현수', '김민기');

-- SELECT FROM WHERE(BETWEEN) 2번
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
FROM A_OUT_D
WHERE INVOICE_NO BETWEEN '#01' AND '#05'
AND ITEM_CD IN ('A', 'B', 'C')
AND ORDER_QTY >= 3;

-- SELECT FROM WHERE(LIKE) 1번
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
FROM A_OUT_M
WHERE INVOICE_NO BETWEEN '#01' AND '#05'
AND (ORDER_NM LIKE '전%' OR ORDER_NM LIKE '권%');

-- SELECT FROM WHERE(LIKE) 2번
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
FROM A_OUT_D
WHERE INVOICE_NO LIKE '#0%'
AND ORDER_QTY >= 3;




