-- SELECT FROM WHERE ORDER BY(ASC, DESC) 1번
SELECT *
FROM A_OUT_D
WHERE INVOICE_NO LIKE '#0%'
AND ORDER_QTY >= 3
ORDER BY ORDER_QTY DESC;

-- SELECT FROM WHERE ORDER BY(ASC, DESC) 2번
SELECT *
FROM A_OUT_D
WHERE INVOICE_NO LIKE '#0%'
AND ORDER_QTY >= 3
ORDER BY ORDER_QTY DESC, ITEM_CD;

-- SELECT FROM WHERE ORDER BY(ASC, DESC) 3번
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
FROM (
SELECT * FROM A_OUT_D
WHERE INVOICE_NO LIKE '#0%'
AND ORDER_QTY >= 2
ORDER BY ORDER_QTY DESC, ITEM_CD)
WHERE ROWNUM <= 3;

-- SELECT 집계함수's FROM WHERE 1번





