SELECT ITEM_CD,       
       ITEM_NM,
      SUM(ORDER_QTY) AS SUM_QTY
FROM LO_OUT_D M1
WHERE INVOICE_NO BETWEEN '346724706262' AND '346724706762'
GROUP BY ITEM_CD, ITEM_NM
ORDER BY ITEM_CD;

SELECT * FROM LO_OUT_D
WHERE ITEM_CD IN ('11947', '11949'); 


-- 2¹ø
SELECT ROWNUM  AS RNK, 
              ITEM_CD, 
           QTY_IN_BOX, 
            ORDER_QTY, 
              BOX_CNT, 
              PCS_CNT, 
          BOX_CNT_TOT
FROM (
SELECT ITEM_CD,
       QTY_IN_BOX,
       ORDER_QTY,
       TRUNC(ORDER_QTY / QTY_IN_BOX) AS BOX_CNT,
       MOD(ORDER_QTY, QTY_IN_BOX) AS PCS_CNT,
       CEIL(ORDER_QTY / QTY_IN_BOX) AS BOX_CNT_TOT
FROM (
SELECT ITEM_CD, 
       ITEM_NM,
       QTY_IN_BOX,
       ORDER_QTY
FROM (
       SELECT ITEM_CD,       
              ITEM_NM,
              QTY_IN_BOX,
        SUM(ORDER_QTY) AS ORDER_QTY
        FROM LO_OUT_D
        WHERE INVOICE_NO BETWEEN '346724706262' AND '346724706762'
        GROUP BY ITEM_CD, ITEM_NM, QTY_IN_BOX
        ORDER BY ORDER_QTY DESC
 )
)
ORDER BY ORDER_QTY DESC
)
WHERE ROWNUM <= 5;



SELECT INVOICE_NO, OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY, OUTBOUND_NO
FROM LO_OUT_M
WHERE INVOICE_NO IN ('346724706214', '346724793596', '346724869970')
ORDER BY OUTBOUND_DATE, INVOICE_NO;


SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'Empty..') AS OUDER_QTY
FROM LO_OUT_D
WHERE INVOICE_NO = '346724706215';



