-- 1번
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M1.INVOICE_NO, D1.LINE_NO, D1.ORDER_QTY
FROM A_OUT_M M1
     JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                    AND D1.INVOICE_NO = M1.INVOICE_NO
WHERE M1.OUTBOUND_DATE = '2023-01-04'
  AND D1.ITEM_CD IN ('B', 'D');
  
-- 2번
 SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, D1.ITEM_CD, 
         SUM(ORDER_QTY) AS SUM_QTY
 FROM A_OUT_M M1
     JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                    AND D1.INVOICE_NO = M1.INVOICE_NO
WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-03' AND '2023-01-04'
  AND D1.ITEM_CD IN ('B', 'D')
GROUP BY M1.BRAND_CD, M1.OUTBOUND_DATE, D1.ITEM_CD;


-- 3번
SELECT M1.*, ROWNUM 
FROM (
             SELECT M1.INVOICE_NO, M1.ORDER_NM, SUM(D1.ORDER_QTY) AS SUM_QTY
             FROM A_OUT_M M1
             JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                            AND D1.INVOICE_NO = M1.INVOICE_NO
             WHERE M1.BRAND_CD = '1001'
             AND   M1.OUTBOUND_DATE BETWEEN '2023-01-04' AND '2023-01-05'
             GROUP BY M1.INVOICE_NO, M1.ORDER_NM
             ORDER BY SUM_QTY DESC
      ) M1
WHERE ROWNUM = 1;

-- 조인 1번
SELECT M1.BRAND_CD, M1.INVOICE_NO, D1.ITEM_CD, A1.ITEM_NM, D1.ORDER_QTY
FROM A_OUT_M M1
     JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                    AND D1.INVOICE_NO = M1.INVOICE_NO
     JOIN A_ITEM A1 ON A1.ITEM_CD = D1.ITEM_CD
                   AND A1.BRAND_CD = M1.BRAND_CD
WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'         
  AND D1.ORDER_QTY >= 3;
  

-- 조인 2번
SELECT M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX, SUM(D1.ORDER_QTY) AS SUM_QTY
FROM A_OUT_M M1
     JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                    AND D1.INVOICE_NO = M1.INVOICE_NO
     JOIN A_ITEM A1 ON A1.ITEM_CD = D1.ITEM_CD
                   AND A1.BRAND_CD = M1.BRAND_CD
WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
GROUP BY M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX; 


-- 조인 3번
SELECT M1.*, 
       TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_QTY,
       MOD(SUM_QTY, QTY_IN_BOX) AS NAT_QTY
FROM (
      SELECT M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX, SUM(D1.ORDER_QTY) AS SUM_QTY
      FROM A_OUT_M M1
      JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                     AND D1.INVOICE_NO = M1.INVOICE_NO
      JOIN A_ITEM A1 ON A1.ITEM_CD = D1.ITEM_CD
                    AND A1.BRAND_CD = M1.BRAND_CD
      WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
      GROUP BY M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX
      ORDER BY TRUNC(SUM_QTY / QTY_IN_BOX) DESC
) M1;

-- 조인 4번
SELECT *
FROM (
SELECT M1.*, 
       TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_QTY,
       MOD(SUM_QTY, QTY_IN_BOX) AS NAT_QTY
       FROM (
             SELECT M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX, SUM(D1.ORDER_QTY) AS SUM_QTY
             FROM A_OUT_M M1
             JOIN A_OUT_D D1 ON D1.BRAND_CD = M1.BRAND_CD
                            AND D1.INVOICE_NO = M1.INVOICE_NO
             JOIN A_ITEM A1 ON A1.ITEM_CD = D1.ITEM_CD
                           AND A1.BRAND_CD = M1.BRAND_CD
             WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
             GROUP BY M1.BRAND_CD, D1.ITEM_CD, A1.ITEM_NM, A1.QTY_IN_BOX
             ORDER BY TRUNC(SUM_QTY / QTY_IN_BOX) DESC
       ) M1
) M2
WHERE ROWNUM <= 3;














