-- CASE문 적용 정렬 1번 문제
SELECT BRAND_CD, 
      INVOICE_NO, 
      LINE_NO, 
      ITEM_CD, 
      ORDER_QTY,
      CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
      WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
      ELSE '상'
      END AS GRADE
FROM A_OUT_D
WHERE BRAND_CD = '1001'
ORDER BY CASE WHEN ITEM_CD = 'C' THEN 1
              ELSE 2 END, ITEM_CD, ORDER_QTY DESC;
              
-- WHERE절, SELECT절에 CASE문 적용하기
SELECT OUTBOUND_DATE,
       COUNT(DISTINCT INVOICE_NO) AS INVOICE_CNT,
       COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN 1 END) AS M1_CNT,
       COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M2%' THEN 1 END) AS M2_CNT 
FROM LO_OUT_M
WHERE OUTBOUND_DATE BETWEEN TO_DATE(TO_CHAR(TO_DATE(:OUT_DATE), 'YYYYMM') || '01', 'YYYY-MM-DD')
                        AND TO_DATE(:OUT_DATE)
  AND OUT_BOX_DIV   LIKE    CASE  :COND
                                  WHEN '0' THEN '%'
                                  WHEN '1' THEN 'D%'
                                  WHEN '2' THEN 'F%'
                                  ELSE '.%'
                            END
 GROUP BY OUTBOUND_DATE
 ORDER BY OUTBOUND_DATE;        
 
-- 이상한 데이터 찾아내기
SELECT ITEM_BAR_CD, 
       COUNT(DISTINCT ITEM_CD) AS ITEM_CNT
FROM LO_OUT_D
GROUP BY ITEM_BAR_CD
HAVING COUNT(DISTINCT ITEM_CD) > 1
ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 2 ELSE 1 END, 
         COUNT(DISTINCT ITEM_CD) DESC;

SELECT SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN SET_QTY END) AS M01,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN SET_QTY END) AS M02,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN SET_QTY END) AS M03,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN SET_QTY END) AS M04,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN SET_QTY END) AS M05,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN SET_QTY END) AS M06,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN SET_QTY END) AS M07,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN SET_QTY END) AS M08,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN SET_QTY END) AS M09,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN SET_QTY END) AS M10,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN SET_QTY END) AS M11,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN SET_QTY END) AS M12
FROM LO_OUT_M
WHERE OUTBOUND_DATE BETWEEN TO_DATE(:OUT_YEAR || '0101', 'YYYY_MM_DD')
                        AND TO_DATE(:OUT_YEAR || '1231', 'YYYY_MM_DD');
              
--          
SELECT OUTBOUND_DATE,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN SET_QTY END) AS M01,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN SET_QTY END) AS M02,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN SET_QTY END) AS M03,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN SET_QTY END) AS M04,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN SET_QTY END) AS M05,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN SET_QTY END) AS M06,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN SET_QTY END) AS M07,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN SET_QTY END) AS M08,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN SET_QTY END) AS M09,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN SET_QTY END) AS M10,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN SET_QTY END) AS M11,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN SET_QTY END) AS M12
FROM LO_OUT_M
WHERE OUTBOUND_DATE BETWEEN TO_DATE(:OUT_YEAR || '0101', 'YYYY_MM_DD')
                        AND TO_DATE(:OUT_YEAR || '1231', 'YYYY_MM_DD')
GROUP BY OUTBOUND_DATE
ORDER BY OUTBOUND_DATE;

--          
SELECT 
       TO_CHAR(OUTBOUND_DATE, 'YYYY') AS YYYY,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN SET_QTY END) AS M01,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN SET_QTY END) AS M02,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN SET_QTY END) AS M03,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN SET_QTY END) AS M04,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN SET_QTY END) AS M05,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN SET_QTY END) AS M06,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN SET_QTY END) AS M07,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN SET_QTY END) AS M08,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN SET_QTY END) AS M09,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN SET_QTY END) AS M10,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN SET_QTY END) AS M11,
       SUM(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN SET_QTY END) AS M12
FROM LO_OUT_M
GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
ORDER BY TO_CHAR(OUTBOUND_DATE, 'YYYY');

--
SELECT INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ORDER_QTY
FROM LO_OUT_D
WHERE INVOICE_NO = '346724706214'
ORDER BY CASE :SORT_TYPE WHEN '1' THEN LINE_NO
                         WHEN '2' THEN ORDER_QTY
                         END, LINE_NO;

          