SELECT * FROM tab;

CREATE TABLE t_test(
    id varchar2(20) PRIMARY KEY,
    name varchar2(30) NOT NULL
);

COMMIT;

SELECT J1.JOB_TITLE, AVG(E1.SALARY)
FROM JOBS J1
JOIN EMPLOYEES E1 ON E1.JOB_ID = J1.JOB_ID 
WHERE E1.SALARY >= :SALARY
GROUP BY J1.JOB_TITLE
ORDER BY AVG(E1.SALARY) DESC;
                    

-- 1번
SELECT TO_CHAR(E1.HIRE_DATE, 'YYYY') AS year, AVG(E1.SALARY) AS AVG
FROM JOBS J1
JOIN EMPLOYEES E1 ON E1.JOB_ID = J1.JOB_ID
WHERE J1.JOB_TITLE = 'Sales Manager'
GROUP BY TO_CHAR(E1.HIRE_DATE, 'YYYY')
ORDER BY TO_CHAR(E1.HIRE_DATE, 'YYYY');

-- 2번
SELECT CITY, 
       AVG,
       CASE WHEN EMPLOYEE < 10 THEN EMPLOYEE END AS EMPLOYEE
FROM (
	SELECT L1.CITY, TRUNC(AVG(E1.SALARY)) AS AVG , COUNT(E1.DEPARTMENT_ID) AS EMPLOYEE
	FROM EMPLOYEES E1
	JOIN DEPARTMENTS D1 ON D1.DEPARTMENT_ID  = E1.DEPARTMENT_ID 
	JOIN LOCATIONS L1 ON L1.LOCATION_ID = D1.LOCATION_ID 
	GROUP BY L1.CITY 
	ORDER BY AVG(E1.SALARY)
) C1;

-- 3번
SELECT E1.EMPLOYEE_ID, TO_CHAR(E1.FIRST_NAME || E1.LAST_NAME)
FROM EMPLOYEES E1
JOIN JOB_HISTORY H1 ON H1.JOB_ID = E1.JOB_ID
WHERE H1.JOB_ID = 'AC_ACCOUNT';

-- 4번
SELECT LAST_NAME, SALARY
FROM EMPLOYEES 
WHERE LAST_NAME IN('Ozer', 'Abel')
ORDER BY SALARY DESC;

-- 5번
SELECT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.LAST_NAME, D1.DEPARTMENT_NAME
FROM EMPLOYEES E1
JOIN DEPARTMENTS D1 ON D1.DEPARTMENT_ID = E1.DEPARTMENT_ID
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '2007';

-- 6번
SELECT 
FROM JOBS J1
JOIN EMPLOYEES E1 ON E















